{% set name = "openlineage-dbt" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage-dbt-{{ version }}.tar.gz
  sha256: 38e7cdba38c7f1b3740f81fc52cddaf58eb8012167d32002137a19e3f7d893ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tqdm >=4.62.0
    - openlineage-integration-common =={{ version }}

test:
  imports:
    - openlineage.common.provider.dbt
  commands:
    - pip check
  requires:
    - pip
    - dbt-core >=1.3.0

about:
  summary: OpenLineage integration with dbt
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-integration-common
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
